const vocabulary = {
    animals: {
        title: 'Animais', icon: '🐾',
        words: [
            { emoji: '🐶', english: 'Dog', phonetic: '/dóg/', portuguese: 'Cachorro', sentence: 'The dog is friendly.', sentenceTranslation: 'O cachorro é amigável.' },
            { emoji: '🐱', english: 'Cat', phonetic: '/kát/', portuguese: 'Gato', sentence: 'The cat sleeps a lot.', sentenceTranslation: 'O gato dorme muito.' },
            { emoji: '🐦', english: 'Bird', phonetic: '/bêrd/', portuguese: 'Pássaro', sentence: 'The bird can fly.', sentenceTranslation: 'O pássaro pode voar.' },
            { emoji: '🐟', english: 'Fish', phonetic: '/físh/', portuguese: 'Peixe', sentence: 'The fish swims.', sentenceTranslation: 'O peixe nada.' },
            { emoji: '🐰', english: 'Rabbit', phonetic: '/rábit/', portuguese: 'Coelho', sentence: 'The rabbit has long ears.', sentenceTranslation: 'O coelho tem orelhas longas.' },
            { emoji: '🐮', english: 'Cow', phonetic: '/káu/', portuguese: 'Vaca', sentence: 'The cow gives milk.', sentenceTranslation: 'A vaca dá leite.' },
            { emoji: '🐷', english: 'Pig', phonetic: '/píg/', portuguese: 'Porco', sentence: 'The pig is pink.', sentenceTranslation: 'O porco é rosa.' },
            { emoji: '🐔', english: 'Chicken', phonetic: '/chíken/', portuguese: 'Galinha', sentence: 'The chicken clucks.', sentenceTranslation: 'A galinha cacareja.' },
            { emoji: '🐴', english: 'Horse', phonetic: '/hórs/', portuguese: 'Cavalo', sentence: 'The horse runs fast.', sentenceTranslation: 'O cavalo corre rápido.' },
            { emoji: '🦁', english: 'Lion', phonetic: '/láion/', portuguese: 'Leão', sentence: 'The lion is king.', sentenceTranslation: 'O leão é o rei.' },
            { emoji: '🐘', english: 'Elephant', phonetic: '/élifant/', portuguese: 'Elefante', sentence: 'The elephant is big.', sentenceTranslation: 'O elefante é grande.' },
            { emoji: '🐵', english: 'Monkey', phonetic: '/mánki/', portuguese: 'Macaco', sentence: 'The monkey likes bananas.', sentenceTranslation: 'O macaco gosta de bananas.' },
            { emoji: '🐻', english: 'Bear', phonetic: '/bêr/', portuguese: 'Urso', sentence: 'The bear is strong.', sentenceTranslation: 'O urso é forte.' },
            { emoji: '🐸', english: 'Frog', phonetic: '/fróg/', portuguese: 'Sapo', sentence: 'The frog jumps.', sentenceTranslation: 'O sapo pula.' },
            { emoji: '🦆', english: 'Duck', phonetic: '/dák/', portuguese: 'Pato', sentence: 'The duck quacks.', sentenceTranslation: 'O pato grasna.' },
            { emoji: '🐑', english: 'Sheep', phonetic: '/shíp/', portuguese: 'Ovelha', sentence: 'The sheep is soft.', sentenceTranslation: 'A ovelha é macia.' },
            { emoji: '🐐', english: 'Goat', phonetic: '/góut/', portuguese: 'Cabra', sentence: 'The goat eats grass.', sentenceTranslation: 'A cabra come grama.' },
            { emoji: '🦉', english: 'Owl', phonetic: '/áol/', portuguese: 'Coruja', sentence: 'The owl is wise.', sentenceTranslation: 'A coruja é sábia.' },
            { emoji: '🦅', english: 'Eagle', phonetic: '/ígol/', portuguese: 'Águia', sentence: 'The eagle flies high.', sentenceTranslation: 'A águia voa alto.' },
            { emoji: '🐺', english: 'Wolf', phonetic: '/uólf/', portuguese: 'Lobo', sentence: 'The wolf howls.', sentenceTranslation: 'O lobo uiva.' },
            { emoji: '🦊', english: 'Fox', phonetic: '/fóks/', portuguese: 'Raposa', sentence: 'The fox is clever.', sentenceTranslation: 'A raposa é esperta.' },
            { emoji: '🐗', english: 'Boar', phonetic: '/bóar/', portuguese: 'Javali', sentence: 'The boar is wild.', sentenceTranslation: 'O javali é selvagem.' },
            { emoji: '🦌', english: 'Deer', phonetic: '/dír/', portuguese: 'Cervo', sentence: 'The deer runs fast.', sentenceTranslation: 'O cervo corre rápido.' },
            { emoji: '🐢', english: 'Turtle', phonetic: '/tértol/', portuguese: 'Tartaruga', sentence: 'The turtle is slow.', sentenceTranslation: 'A tartaruga é lenta.' },
            { emoji: '🐊', english: 'Crocodile', phonetic: '/krókodail/', portuguese: 'Crocodilo', sentence: 'The crocodile is scary.', sentenceTranslation: 'O crocodilo é assustador.' }
        ]
    },
    food: {
        title: 'Comidas', icon: '🍎',
        words: [
            { emoji: '🍎', english: 'Apple', phonetic: '/ápol/', portuguese: 'Maçã', sentence: 'I eat an apple.', sentenceTranslation: 'Eu como uma maçã.' },
            { emoji: '🍌', english: 'Banana', phonetic: '/banana/', portuguese: 'Banana', sentence: 'The banana is yellow.', sentenceTranslation: 'A banana é amarela.' },
            { emoji: '🍊', english: 'Orange', phonetic: '/órinj/', portuguese: 'Laranja', sentence: 'Orange juice is good.', sentenceTranslation: 'O suco de laranja é bom.' },
            { emoji: '🍇', english: 'Grapes', phonetic: '/gréps/', portuguese: 'Uva', sentence: 'Grapes are sweet.', sentenceTranslation: 'As uvas são doces.' },
            { emoji: '🍓', english: 'Strawberry', phonetic: '/stróbêri/', portuguese: 'Morango', sentence: 'I love strawberries.', sentenceTranslation: 'Eu amo morangos.' },
            { emoji: '🍕', english: 'Pizza', phonetic: '/pítsa/', portuguese: 'Pizza', sentence: 'Pizza is delicious.', sentenceTranslation: 'A pizza é deliciosa.' },
            { emoji: '🍔', english: 'Hamburger', phonetic: '/hámburguer/', portuguese: 'Hambúrguer', sentence: 'I want a hamburger.', sentenceTranslation: 'Eu quero um hambúrguer.' },
            { emoji: '🥪', english: 'Sandwich', phonetic: '/sán-uich/', portuguese: 'Sanduíche', sentence: 'The sandwich is tasty.', sentenceTranslation: 'O sanduíche é gostoso.' },
            { emoji: '🧀', english: 'Cheese', phonetic: '/chíz/', portuguese: 'Queijo', sentence: 'Cheese is yummy.', sentenceTranslation: 'O queijo é gostoso.' },
            { emoji: '🥚', english: 'Egg', phonetic: '/ég/', portuguese: 'Ovo', sentence: 'I eat eggs for breakfast.', sentenceTranslation: 'Eu como ovos no café da manhã.' },
            { emoji: '🍞', english: 'Bread', phonetic: '/bréd/', portuguese: 'Pão', sentence: 'Bread is soft.', sentenceTranslation: 'O pão é macio.' },
            { emoji: '🥛', english: 'Milk', phonetic: '/mílk/', portuguese: 'Leite', sentence: 'Milk is healthy.', sentenceTranslation: 'O leite é saudável.' },
            { emoji: '💧', english: 'Water', phonetic: '/uóter/', portuguese: 'Água', sentence: 'Water is refreshing.', sentenceTranslation: 'A água é refrescante.' },
            { emoji: '🧃', english: 'Juice', phonetic: '/djús/', portuguese: 'Suco', sentence: 'Juice is sweet.', sentenceTranslation: 'O suco é doce.' },
            { emoji: '☕', english: 'Coffee', phonetic: '/cófi/', portuguese: 'Café', sentence: 'Coffee is hot.', sentenceTranslation: 'O café é quente.' },
            { emoji: '🍫', english: 'Chocolate', phonetic: '/chokolát/', portuguese: 'Chocolate', sentence: 'Chocolate is sweet.', sentenceTranslation: 'O chocolate é doce.' },
            { emoji: '🍦', english: 'Ice Cream', phonetic: '/áis-krím/', portuguese: 'Sorvete', sentence: 'Ice cream is cold.', sentenceTranslation: 'O sorvete é frio.' },
            { emoji: '🍪', english: 'Cookie', phonetic: '/kúki/', portuguese: 'Biscoito', sentence: 'The cookie is crunchy.', sentenceTranslation: 'O biscoito é crocante.' },
            { emoji: '🧁', english: 'Cupcake', phonetic: '/kápkeik/', portuguese: 'Cupcake', sentence: 'The cupcake is sweet.', sentenceTranslation: 'O cupcake é doce.' },
            { emoji: '🍩', english: 'Donut', phonetic: '/dónat/', portuguese: 'Rosquinha', sentence: 'The donut is round.', sentenceTranslation: 'A rosquinha é redonda.' },
            { emoji: '🌮', english: 'Taco', phonetic: '/táko/', portuguese: 'Taco', sentence: 'The taco is spicy.', sentenceTranslation: 'O taco é picante.' },
            { emoji: '🍜', english: 'Noodles', phonetic: '/núdols/', portuguese: 'Macarrão', sentence: 'Noodles are tasty.', sentenceTranslation: 'O macarrão é gostoso.' },
            { emoji: '🥐', english: 'Croissant', phonetic: '/kruasã/', portuguese: 'Croissant', sentence: 'The croissant is flaky.', sentenceTranslation: 'O croissant é folhado.' },
            { emoji: '🥞', english: 'Pancake', phonetic: '/pánkeik/', portuguese: 'Panqueca', sentence: 'Pancakes for breakfast.', sentenceTranslation: 'Panquecas para o café da manhã.' },
            { emoji: '🧈', english: 'Butter', phonetic: '/bátor/', portuguese: 'Manteiga', sentence: 'Butter on bread.', sentenceTranslation: 'Manteiga no pão.' }
        ]
    },
    colors: {
        title: 'Cores', icon: '🎨',
        words: [
            { emoji: '🔴', english: 'Red', phonetic: '/réd/', portuguese: 'Vermelho', sentence: 'The car is red.', sentenceTranslation: 'O carro é vermelho.' },
            { emoji: '🔵', english: 'Blue', phonetic: '/blú/', portuguese: 'Azul', sentence: 'The sky is blue.', sentenceTranslation: 'O céu é azul.' },
            { emoji: '🟢', english: 'Green', phonetic: '/grín/', portuguese: 'Verde', sentence: 'The grass is green.', sentenceTranslation: 'A grama é verde.' },
            { emoji: '🟡', english: 'Yellow', phonetic: '/yélou/', portuguese: 'Amarelo', sentence: 'The sun is yellow.', sentenceTranslation: 'O sol é amarelo.' },
            { emoji: '🟠', english: 'Orange', phonetic: '/órinj/', portuguese: 'Laranja', sentence: 'The orange is orange.', sentenceTranslation: 'A laranja é laranja.' },
            { emoji: '🟣', english: 'Purple', phonetic: '/pôrpol/', portuguese: 'Roxo', sentence: 'The flower is purple.', sentenceTranslation: 'A flor é roxa.' },
            { emoji: '⚪', english: 'White', phonetic: '/uáit/', portuguese: 'Branco', sentence: 'Snow is white.', sentenceTranslation: 'A neve é branca.' },
            { emoji: '⚫', english: 'Black', phonetic: '/blák/', portuguese: 'Preto', sentence: 'Night is black.', sentenceTranslation: 'A noite é preta.' },
            { emoji: '🟤', english: 'Brown', phonetic: '/bráun/', portuguese: 'Marrom', sentence: 'The dog is brown.', sentenceTranslation: 'O cachorro é marrom.' },
            { emoji: '🩷', english: 'Pink', phonetic: '/pínk/', portuguese: 'Rosa', sentence: 'The pig is pink.', sentenceTranslation: 'O porco é rosa.' },
            { emoji: '🩵', english: 'Light Blue', phonetic: '/láit blú/', portuguese: 'Azul Claro', sentence: 'Water is light blue.', sentenceTranslation: 'A água é azul clara.' },
            { emoji: '🩶', english: 'Gray', phonetic: '/gréi/', portuguese: 'Cinza', sentence: 'The elephant is gray.', sentenceTranslation: 'O elefante é cinza.' },
            { emoji: '💎', english: 'Cyan', phonetic: '/sáian/', portuguese: 'Ciano', sentence: 'The pool is cyan.', sentenceTranslation: 'A piscina é ciano.' },
            { emoji: '🌸', english: 'Magenta', phonetic: '/magentá/', portuguese: 'Magenta', sentence: 'The flower is magenta.', sentenceTranslation: 'A flor é magenta.' },
            { emoji: '🍋', english: 'Lime', phonetic: '/láim/', portuguese: 'Lima', sentence: 'The lime is sour.', sentenceTranslation: 'A lima é azeda.' },
            { emoji: '🍑', english: 'Peach', phonetic: '/pítch/', portuguese: 'Pêssego', sentence: 'The peach is soft.', sentenceTranslation: 'O pêssego é macio.' },
            { emoji: '🫐', english: 'Indigo', phonetic: '/índigo/', portuguese: 'Índigo', sentence: 'The sky is indigo.', sentenceTranslation: 'O céu é indigo.' },
            { emoji: '🥥', english: 'Beige', phonetic: '/béj/', portuguese: 'Bege', sentence: 'The wall is beige.', sentenceTranslation: 'A parede é bege.' },
            { emoji: '🥑', english: 'Olive', phonetic: '/ólív/', portuguese: 'Oliva', sentence: 'The olive is green.', sentenceTranslation: 'A azeitona é verde.' },
            { emoji: '🌰', english: 'Maroon', phonetic: '/marún/', portuguese: 'Grená', sentence: 'The bag is maroon.', sentenceTranslation: 'A bolsa é grená.' },
            { emoji: '🧊', english: 'Teal', phonetic: '/tíl/', portuguese: 'Azul-petróleo', sentence: 'The water is teal.', sentenceTranslation: 'A água é azul-petróleo.' },
            { emoji: '🧤', english: 'Silver', phonetic: '/sílver/', portuguese: 'Prata', sentence: 'The ring is silver.', sentenceTranslation: 'O anel é de prata.' },
            { emoji: '🍯', english: 'Gold', phonetic: '/góld/', portuguese: 'Dourado', sentence: 'The trophy is gold.', sentenceTranslation: 'O troféu é dourado.' },
            { emoji: '🌫️', english: 'Ash', phonetic: '/ásh/', portuguese: 'Cinza Claro', sentence: 'Ash is light gray.', sentenceTranslation: 'Cinza é cinza claro.' },
            { emoji: '🥀', english: 'Burgundy', phonetic: '/bér-gundi/', portuguese: 'Borgonha', sentence: 'The wine is burgundy.', sentenceTranslation: 'O vinho é borgonha.' }
        ]
    },
    numbers: {
        title: 'Números', icon: '🔢',
        words: [
            { emoji: '1️⃣', english: 'One', phonetic: '/uán/', portuguese: 'Um', sentence: 'I have one cat.', sentenceTranslation: 'Eu tenho um gato.' },
            { emoji: '2️⃣', english: 'Two', phonetic: '/tú/', portuguese: 'Dois', sentence: 'I have two hands.', sentenceTranslation: 'Eu tenho duas mãos.' },
            { emoji: '3️⃣', english: 'Three', phonetic: '/trí/', portuguese: 'Três', sentence: 'Three little pigs.', sentenceTranslation: 'Três porquinhos.' },
            { emoji: '4️⃣', english: 'Four', phonetic: '/fór/', portuguese: 'Quatro', sentence: 'Four seasons.', sentenceTranslation: 'Quatro estações.' },
            { emoji: '5️⃣', english: 'Five', phonetic: '/fáiv/', portuguese: 'Cinco', sentence: 'Five fingers.', sentenceTranslation: 'Cinco dedos.' },
            { emoji: '6️⃣', english: 'Six', phonetic: '/síks/', portuguese: 'Seis', sentence: 'Six eggs in a box.', sentenceTranslation: 'Seis ovos numa caixa.' },
            { emoji: '7️⃣', english: 'Seven', phonetic: '/séven/', portuguese: 'Sete', sentence: 'Seven days a week.', sentenceTranslation: 'Sete dias na semana.' },
            { emoji: '8️⃣', english: 'Eight', phonetic: '/éit/', portuguese: 'Oito', sentence: 'Eight legs on spider.', sentenceTranslation: 'Oito patas na aranha.' },
            { emoji: '9️⃣', english: 'Nine', phonetic: '/náin/', portuguese: 'Nove', sentence: 'Nine lives for cat.', sentenceTranslation: 'Nove vidas para o gato.' },
            { emoji: '🔟', english: 'Ten', phonetic: '/tén/', portuguese: 'Dez', sentence: 'I have ten toes.', sentenceTranslation: 'Eu tenho dez dedos dos pés.' },
            { emoji: '💯', english: 'Hundred', phonetic: '/hándred/', portuguese: 'Cem', sentence: 'One hundred points!', sentenceTranslation: 'Cem pontos!' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣', english: 'Thousand', phonetic: '/táu-zand/', portuguese: 'Mil', sentence: 'A thousand stars.', sentenceTranslation: 'Mil estrelas.' },
            { emoji: '➕', english: 'Plus', phonetic: '/plás/', portuguese: 'Mais', sentence: 'Two plus two.', sentenceTranslation: 'Dois mais dois.' },
            { emoji: '➖', english: 'Minus', phonetic: '/máinas/', portuguese: 'Menos', sentence: 'Five minus one.', sentenceTranslation: 'Cinco menos um.' },
            { emoji: '➗', english: 'Divide', phonetic: '/diváid/', portuguese: 'Dividir', sentence: 'Divide by two.', sentenceTranslation: 'Dividir por dois.' },
            { emoji: '✖️', english: 'Multiply', phonetic: '/mátiploai/', portuguese: 'Multiplicar', sentence: 'Multiply by ten.', sentenceTranslation: 'Multiplicar por dez.' },
            { emoji: '0️⃣', english: 'Zero', phonetic: '/zíro/', portuguese: 'Zero', sentence: 'I have zero apples.', sentenceTranslation: 'Eu não tenho nenhuma maçã.' },
            { emoji: '1️⃣1️⃣', english: 'Eleven', phonetic: '/iléven/', portuguese: 'Onze', sentence: 'Eleven players.', sentenceTranslation: 'Onze jogadores.' },
            { emoji: '1️⃣2️⃣', english: 'Twelve', phonetic: '/tuélv/', portuguese: 'Doze', sentence: 'Twelve months.', sentenceTranslation: 'Doze meses.' },
            { emoji: '🔟0️⃣', english: 'Twenty', phonetic: '/tuénty/', portuguese: 'Vinte', sentence: 'Twenty students.', sentenceTranslation: 'Vinte estudantes.' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣0️⃣', english: 'Ten Thousand', phonetic: '/tén táu-zand/', portuguese: 'Dez Mil', sentence: 'Ten thousand people.', sentenceTranslation: 'Dez mil pessoas.' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣0️⃣0️⃣0️⃣', english: 'Million', phonetic: '/mílion/', portuguese: 'Milhão', sentence: 'A million stars.', sentenceTranslation: 'Um milhão de estrelas.' },
            { emoji: '🧮', english: 'Billion', phonetic: '/bílion/', portuguese: 'Bilhão', sentence: 'A billion dollars.', sentenceTranslation: 'Um bilhão de dólares.' },
            { emoji: '📈', english: 'First', phonetic: '/férst/', portuguese: 'Primeiro', sentence: 'I am first!', sentenceTranslation: 'Eu sou o primeiro!' }
        ]
    },
    body: {
        title: 'Corpo', icon: '🦴',
        words: [
            { emoji: '👀', english: 'Eyes', phonetic: '/áis/', portuguese: 'Olhos', sentence: 'I have two eyes.', sentenceTranslation: 'Eu tenho dois olhos.' },
            { emoji: '👃', english: 'Nose', phonetic: '/nóz/', portuguese: 'Nariz', sentence: 'My nose is small.', sentenceTranslation: 'Meu nariz é pequeno.' },
            { emoji: '👂', english: 'Ear', phonetic: '/ír/', portuguese: 'Orelha', sentence: 'I hear with ears.', sentenceTranslation: 'Eu ouço com as orelhas.' },
            { emoji: '👄', english: 'Mouth', phonetic: '/máus/', portuguese: 'Boca', sentence: 'I eat with mouth.', sentenceTranslation: 'Eu como com a boca.' },
            { emoji: '🦷', english: 'Tooth', phonetic: '/túth/', portuguese: 'Dente', sentence: 'Brush your teeth.', sentenceTranslation: 'Escove seus dentes.' },
            { emoji: '✋', english: 'Hand', phonetic: '/hánd/', portuguese: 'Mão', sentence: 'Shake my hand.', sentenceTranslation: 'Aperte minha mão.' },
            { emoji: '👆', english: 'Finger', phonetic: '/fínguer/', portuguese: 'Dedo', sentence: 'Point with finger.', sentenceTranslation: 'Aponte com o dedo.' },
            { emoji: '🦵', english: 'Leg', phonetic: '/lég/', portuguese: 'Perna', sentence: 'I run with legs.', sentenceTranslation: 'Eu corro com as pernas.' },
            { emoji: '🦶', english: 'Foot', phonetic: '/fút/', portuguese: 'Pé', sentence: 'My foot is big.', sentenceTranslation: 'Meu pé é grande.' },
            { emoji: '💪', english: 'Arm', phonetic: '/árm/', portuguese: 'Braço', sentence: 'Strong arms!', sentenceTranslation: 'Braços fortes!' },
            { emoji: '🧠', english: 'Brain', phonetic: '/bréin/', portuguese: 'Cérebro', sentence: 'Use your brain.', sentenceTranslation: 'Use seu cérebro.' },
            { emoji: '❤️', english: 'Heart', phonetic: '/hárt/', portuguese: 'Coração', sentence: 'My heart beats fast.', sentenceTranslation: 'Meu coração bate rápido.' },
            { emoji: '👄', english: 'Lips', phonetic: '/líps/', portuguese: 'Lábios', sentence: 'My lips are soft.', sentenceTranslation: 'Meus lábios são macios.' },
            { emoji: '👅', english: 'Tongue', phonetic: '/táng/', portuguese: 'Língua', sentence: 'Taste with tongue.', sentenceTranslation: 'Prove com a língua.' },
            { emoji: '💇', english: 'Hair', phonetic: '/hér/', portuguese: 'Cabelo', sentence: 'My hair is long.', sentenceTranslation: 'Meu cabelo é longo.' },
            { emoji: '🤚', english: 'Palm', phonetic: '/pám/', portuguese: 'Palma', sentence: 'Read your palm.', sentenceTranslation: 'Leia sua palma.' },
            { emoji: '🫁', english: 'Lungs', phonetic: '/lángz/', portuguese: 'Pulmões', sentence: 'Breathe with lungs.', sentenceTranslation: 'Respire com os pulmões.' },
            { emoji: '🦴', english: 'Bone', phonetic: '/bón/', portuguese: 'Osso', sentence: 'Bones are strong.', sentenceTranslation: 'Os ossos são fortes.' },
            { emoji: '🩸', english: 'Blood', phonetic: '/blád/', portuguese: 'Sangue', sentence: 'Blood is red.', sentenceTranslation: 'O sangue é vermelho.' },
            { emoji: '💅', english: 'Nail', phonetic: '/néil/', portuguese: 'Unha', sentence: 'Cut your nails.', sentenceTranslation: 'Corte suas unhas.' },
            { emoji: '🦷', english: 'Teeth', phonetic: '/títs/', portuguese: 'Dentes', sentence: 'Brush your teeth.', sentenceTranslation: 'Escove seus dentes.' },
            { emoji: '👂', english: 'Earlobe', phonetic: '/írlob/', portuguese: 'Lóbulo', sentence: 'Earrings on earlobe.', sentenceTranslation: 'Brincos no lóbulo.' },
            { emoji: '👁️', english: 'Eyebrow', phonetic: '/ái-brau/', portuguese: 'Sobrancelha', sentence: 'Raise your eyebrow.', sentenceTranslation: 'Levante sua sobrancelha.' },
            { emoji: '🫀', english: 'Vein', phonetic: '/véin/', portuguese: 'Veia', sentence: 'Veins carry blood.', sentenceTranslation: 'As veias carregam sangue.' },
            { emoji: '🦴', english: 'Skull', phonetic: '/skál/', portuguese: 'Crânio', sentence: 'Protect your skull.', sentenceTranslation: 'Proteja seu crânio.' }
        ]
    },
    objects: {
        title: 'Objetos', icon: '⚽',
        words: [
            { emoji: '⚽', english: 'Ball', phonetic: '/ból/', portuguese: 'Bola', sentence: 'Kick the ball.', sentenceTranslation: 'Chute a bola.' },
            { emoji: '📚', english: 'Book', phonetic: '/búk/', portuguese: 'Livro', sentence: 'Read the book.', sentenceTranslation: 'Leia o livro.' },
            { emoji: '✏️', english: 'Pencil', phonetic: '/pên-sol/', portuguese: 'Lápis', sentence: 'Write with pencil.', sentenceTranslation: 'Escreva com lápis.' },
            { emoji: '🎒', english: 'Backpack', phonetic: '/bák-pak/', portuguese: 'Mochila', sentence: 'Carry your backpack.', sentenceTranslation: 'Carregue sua mochila.' },
            { emoji: '💻', english: 'Computer', phonetic: '/kom-piú-ter/', portuguese: 'Computador', sentence: 'Use the computer.', sentenceTranslation: 'Use o computador.' },
            { emoji: '📱', english: 'Phone', phonetic: '/fón/', portuguese: 'Celular', sentence: 'Answer the phone.', sentenceTranslation: 'Atenda o telefone.' },
            { emoji: '🏠', english: 'House', phonetic: '/háus/', portuguese: 'Casa', sentence: 'This is my house.', sentenceTranslation: 'Esta é minha casa.' },
            { emoji: '🚗', english: 'Car', phonetic: '/kár/', portuguese: 'Carro', sentence: 'The car is fast.', sentenceTranslation: 'O carro é rápido.' },
            { emoji: '🚌', english: 'Bus', phonetic: '/bás/', portuguese: 'Ônibus', sentence: 'Take the bus.', sentenceTranslation: 'Pegue o ônibus.' },
            { emoji: '✈️', english: 'Airplane', phonetic: '/éer-pléin/', portuguese: 'Avião', sentence: 'The airplane flies.', sentenceTranslation: 'O avião voa.' },
            { emoji: '🚂', english: 'Train', phonetic: '/tréin/', portuguese: 'Trem', sentence: 'The train goes fast.', sentenceTranslation: 'O trem vai rápido.' },
            { emoji: '🚲', english: 'Bicycle', phonetic: '/báisikol/', portuguese: 'Bicicleta', sentence: 'Ride the bicycle.', sentenceTranslation: 'Ande de bicicleta.' },
            { emoji: '🔑', english: 'Key', phonetic: '/kí/', portuguese: 'Chave', sentence: 'Unlock the door.', sentenceTranslation: 'Destrave a porta.' },
            { emoji: '🚪', english: 'Door', phonetic: '/dór/', portuguese: 'Porta', sentence: 'Open the door.', sentenceTranslation: 'Abra a porta.' },
            { emoji: '🪟', english: 'Window', phonetic: '/uíndo/', portuguese: 'Janela', sentence: 'Close the window.', sentenceTranslation: 'Feche a janela.' },
            { emoji: '🛏️', english: 'Bed', phonetic: '/béd/', portuguese: 'Cama', sentence: 'Sleep in bed.', sentenceTranslation: 'Durma na cama.' },
            { emoji: '🪑', english: 'Chair', phonetic: '/tshér/', portuguese: 'Cadeira', sentence: 'Sit on chair.', sentenceTranslation: 'Sente na cadeira.' },
            { emoji: '🪑', english: 'Table', phonetic: '/téibol/', portuguese: 'Mesa', sentence: 'Eat at table.', sentenceTranslation: 'Coma na mesa.' },
            { emoji: '🛋️', english: 'Sofa', phonetic: '/sófa/', portuguese: 'Sofá', sentence: 'Relax on sofa.', sentenceTranslation: 'Relaxe no sofá.' },
            { emoji: '🪞', english: 'Mirror', phonetic: '/míror/', portuguese: 'Espelho', sentence: 'Look in mirror.', sentenceTranslation: 'Olhe no espelho.' },
            { emoji: '🧸', english: 'Toy', phonetic: '/tóy/', portuguese: 'Brinquedo', sentence: 'Play with toy.', sentenceTranslation: 'Brinque com o brinquedo.' },
            { emoji: '🎁', english: 'Gift', phonetic: '/gift/', portuguese: 'Presente', sentence: 'Open the gift.', sentenceTranslation: 'Abra o presente.' },
            { emoji: '🎈', english: 'Balloon', phonetic: '/balún/', portuguese: 'Balão', sentence: 'The balloon floats.', sentenceTranslation: 'O balão flutua.' },
            { emoji: '🎯', english: 'Target', phonetic: '/tárget/', portuguese: 'Alvo', sentence: 'Hit the target.', sentenceTranslation: 'Acerte o alvo.' },
            { emoji: '🧲', english: 'Magnet', phonetic: '/mágnet/', portuguese: 'Imã', sentence: 'The magnet sticks.', sentenceTranslation: 'O imã gruda.' }
        ]
    },
    family: {
        title: 'Família', icon: '👨‍👩‍👧',
        words: [
            { emoji: '👨', english: 'Father', phonetic: '/fá-zer/', portuguese: 'Pai', sentence: 'My father is tall.', sentenceTranslation: 'Meu pai é alto.' },
            { emoji: '👩', english: 'Mother', phonetic: '/má-zer/', portuguese: 'Mãe', sentence: 'My mother is kind.', sentenceTranslation: 'Minha mãe é gentil.' },
            { emoji: '👦', english: 'Son', phonetic: '/són/', portuguese: 'Filho', sentence: 'He is my son.', sentenceTranslation: 'Ele é meu filho.' },
            { emoji: '👧', english: 'Daughter', phonetic: '/dó-ter/', portuguese: 'Filha', sentence: 'She is my daughter.', sentenceTranslation: 'Ela é minha filha.' },
            { emoji: '👴', english: 'Grandfather', phonetic: '/gránd-fá-zer/', portuguese: 'Avô', sentence: 'My grandfather is old.', sentenceTranslation: 'Meu avô é idoso.' },
            { emoji: '👵', english: 'Grandmother', phonetic: '/gránd-má-zer/', portuguese: 'Avó', sentence: 'My grandmother bakes.', sentenceTranslation: 'Minha avó assa bolo.' },
            { emoji: '👶', english: 'Baby', phonetic: '/béibi/', portuguese: 'Bebê', sentence: 'The baby is cute.', sentenceTranslation: 'O bebê é fofo.' },
            { emoji: '👫', english: 'Brother', phonetic: '/brá-zer/', portuguese: 'Irmão', sentence: 'My brother plays.', sentenceTranslation: 'Meu irmão brinca.' },
            { emoji: '👭', english: 'Sister', phonetic: '/sí-ster/', portuguese: 'Irmã', sentence: 'My sister sings.', sentenceTranslation: 'Minha irmã canta.' },
            { emoji: '👨‍👩‍👧‍👦', english: 'Family', phonetic: '/fá-mi-li/', portuguese: 'Família', sentence: 'I love my family.', sentenceTranslation: 'Eu amo minha família.' },
            { emoji: '👨‍👦', english: 'Uncle', phonetic: '/ún-kol/', portuguese: 'Tio', sentence: 'My uncle visits.', sentenceTranslation: 'Meu tio visita.' },
            { emoji: '👩‍👧', english: 'Aunt', phonetic: '/ánt/', portuguese: 'Tia', sentence: 'My aunt bakes cakes.', sentenceTranslation: 'Minha tia assa bolos.' },
            { emoji: '💑', english: 'Couple', phonetic: '/kápol/', portuguese: 'Casal', sentence: 'They are a couple.', sentenceTranslation: 'Eles são um casal.' },
            { emoji: '🧑‍🤝‍🧑', english: 'Cousins', phonetic: '/kázins/', portuguese: 'Primos', sentence: 'We are cousins.', sentenceTranslation: 'Nós somos primos.' },
            { emoji: '👰', english: 'Wife', phonetic: '/uáif/', portuguese: 'Esposa', sentence: 'My wife is kind.', sentenceTranslation: 'Minha esposa é gentil.' },
            { emoji: '🤵', english: 'Husband', phonetic: '/hásband/', portuguese: 'Marido', sentence: 'My husband is tall.', sentenceTranslation: 'Meu marido é alto.' },
            { emoji: '🧓', english: 'Elder', phonetic: '/élder/', portuguese: 'Idoso', sentence: 'Respect your elder.', sentenceTranslation: 'Respeite seus idosos.' },
            { emoji: '👪', english: 'Parents', phonetic: '/pérents/', portuguese: 'Pais', sentence: 'My parents love me.', sentenceTranslation: 'Meus pais me amam.' },
            { emoji: '👶', english: 'Newborn', phonetic: '/niúbórn/', portuguese: 'Recém-nascido', sentence: 'The newborn sleeps.', sentenceTranslation: 'O recém-nascido dorme.' },
            { emoji: '🧑‍🍼', english: 'Nephew', phonetic: '/néfiu/', portuguese: 'Sobrinho', sentence: 'My nephew is cute.', sentenceTranslation: 'Meu sobrinho é fofo.' },
            { emoji: '👩‍👧', english: 'Niece', phonetic: '/nís/', portuguese: 'Sobrinha', sentence: 'My niece is smart.', sentenceTranslation: 'Minha sobrinha é esperta.' },
            { emoji: '👨‍👩‍👧', english: 'In-laws', phonetic: '/ín-lós/', portuguese: 'Sogros', sentence: 'Visit the in-laws.', sentenceTranslation: 'Visite os sogros.' },
            { emoji: '💑', english: 'Stepfather', phonetic: '/stép-fá-zer/', portuguese: 'Padrasto', sentence: 'My stepfather is nice.', sentenceTranslation: 'Meu padrasto é legal.' },
            { emoji: '👩‍👧', english: 'Stepmother', phonetic: '/stép-má-zer/', portuguese: 'Madrasta', sentence: 'My stepmother bakes.', sentenceTranslation: 'Minha madrasta assa.' },
            { emoji: '👶', english: 'Stepsibling', phonetic: '/stép-sibling/', portuguese: 'Irmão/a de outro pai', sentence: 'My stepsibling plays.', sentenceTranslation: 'Meu/meia irmão/ã brinca.' }
        ]
    },
    clothes: {
        title: 'Roupas', icon: '👕',
        words: [
            { emoji: '👕', english: 'Shirt', phonetic: '/shêrt/', portuguese: 'Camisa', sentence: 'Wear your shirt.', sentenceTranslation: 'Use sua camisa.' },
            { emoji: '👖', english: 'Pants', phonetic: '/pánts/', portuguese: 'Calça', sentence: 'Put on your pants.', sentenceTranslation: 'Coloque sua calça.' },
            { emoji: '👗', english: 'Dress', phonetic: '/drés/', portuguese: 'Vestido', sentence: 'The dress is pretty.', sentenceTranslation: 'O vestido é bonito.' },
            { emoji: '👟', english: 'Shoes', phonetic: '/shús/', portuguese: 'Sapatos', sentence: 'Tie your shoes.', sentenceTranslation: 'Amarre seus sapatos.' },
            { emoji: '🧢', english: 'Hat', phonetic: '/hát/', portuguese: 'Boné', sentence: 'Wear your hat.', sentenceTranslation: 'Use seu boné.' },
            { emoji: '🧣', english: 'Scarf', phonetic: '/skárf/', portuguese: 'Cachecol', sentence: 'The scarf is warm.', sentenceTranslation: 'O cachecol é quente.' },
            { emoji: '🧤', english: 'Gloves', phonetic: '/glóvs/', portuguese: 'Luvas', sentence: 'Wear your gloves.', sentenceTranslation: 'Use suas luvas.' },
            { emoji: '🧥', english: 'Coat', phonetic: '/kót/', portuguese: 'Casaco', sentence: 'Put on your coat.', sentenceTranslation: 'Coloque seu casaco.' },
            { emoji: '🩳', english: 'Shorts', phonetic: '/shórts/', portuguese: 'Shorts', sentence: 'Wear your shorts.', sentenceTranslation: 'Use seus shorts.' },
            { emoji: '👚', english: 'Blouse', phonetic: '/bláuz/', portuguese: 'Blusa', sentence: 'The blouse is nice.', sentenceTranslation: 'A blusa é legal.' },
            { emoji: '🧦', english: 'Socks', phonetic: '/sóks/', portuguese: 'Meias', sentence: 'Wear your socks.', sentenceTranslation: 'Use suas meias.' },
            { emoji: '👜', english: 'Bag', phonetic: '/bág/', portuguese: 'Bolsa', sentence: 'Carry your bag.', sentenceTranslation: 'Carregue sua bolsa.' },
            { emoji: '👔', english: 'Tie', phonetic: '/táy/', portuguese: 'Gravata', sentence: 'Wear your tie.', sentenceTranslation: 'Use sua gravata.' },
            { emoji: '👖', english: 'Jeans', phonetic: '/djíns/', portuguese: 'Calça Jeans', sentence: 'Wear your jeans.', sentenceTranslation: 'Use sua calça jeans.' },
            { emoji: '🧥', english: 'Jacket', phonetic: '/djákit/', portuguese: 'Jaqueta', sentence: 'Put on your jacket.', sentenceTranslation: 'Coloque sua jaqueta.' },
            { emoji: '👗', english: 'Skirt', phonetic: '/skért/', portuguese: 'Saias', sentence: 'The skirt is cute.', sentenceTranslation: 'A saia é fofa.' },
            { emoji: '👙', english: 'Swimsuit', phonetic: '/suímsuit/', portuguese: 'Maiô', sentence: 'Wear your swimsuit.', sentenceTranslation: 'Use seu maiô.' },
            { emoji: '👞', english: 'Boots', phonetic: '/búts/', portuguese: 'Botas', sentence: 'Put on your boots.', sentenceTranslation: 'Coloque suas botas.' },
            { emoji: '🩴', english: 'Sandals', phonetic: '/sándols/', portuguese: 'Sandálias', sentence: 'Wear your sandals.', sentenceTranslation: 'Use suas sandálias.' },
            { emoji: '🧶', english: 'Sweater', phonetic: '/suéter/', portuguese: 'Suéter', sentence: 'The sweater is warm.', sentenceTranslation: 'O suéter é quente.' },
            { emoji: '🩱', english: 'Uniform', phonetic: '/iúnifórm/', portuguese: 'Uniforme', sentence: 'Wear your uniform.', sentenceTranslation: 'Use seu uniforme.' },
            { emoji: '🎒', english: 'Apron', phonetic: '/épron/', portuguese: 'Avental', sentence: 'Wear your apron.', sentenceTranslation: 'Use seu avental.' },
            { emoji: '👔', english: 'Suit', phonetic: '/siút/', portuguese: 'Terno', sentence: 'The suit is formal.', sentenceTranslation: 'O terno é formal.' },
            { emoji: '👗', english: 'Costume', phonetic: '/kóstiúm/', portuguese: 'Fantasia', sentence: 'Wear your costume.', sentenceTranslation: 'Use sua fantasia.' },
            { emoji: '🧣', english: 'Beanie', phonetic: '/bíni/', portuguese: 'Gorro', sentence: 'Wear your beanie.', sentenceTranslation: 'Use seu gorro.' }
        ]
    },
    weather: {
        title: 'Clima', icon: '☀️',
        words: [
            { emoji: '☀️', english: 'Sun', phonetic: '/són/', portuguese: 'Sol', sentence: 'The sun is hot.', sentenceTranslation: 'O sol é quente.' },
            { emoji: '🌧️', english: 'Rain', phonetic: '/réin/', portuguese: 'Chuva', sentence: 'The rain is falling.', sentenceTranslation: 'A chuva está caindo.' },
            { emoji: '❄️', english: 'Snow', phonetic: '/snóu/', portuguese: 'Neve', sentence: 'The snow is cold.', sentenceTranslation: 'A neve é fria.' },
            { emoji: '🌤️', english: 'Cloud', phonetic: '/kláud/', portuguese: 'Nuvem', sentence: 'The cloud is white.', sentenceTranslation: 'A nuvem é branca.' },
            { emoji: '💨', english: 'Wind', phonetic: '/uind/', portuguese: 'Vento', sentence: 'The wind blows.', sentenceTranslation: 'O vento sopra.' },
            { emoji: '🌈', english: 'Rainbow', phonetic: '/réinbóu/', portuguese: 'Arco-íris', sentence: 'The rainbow is colorful.', sentenceTranslation: 'O arco-íris é colorido.' },
            { emoji: '⛈️', english: 'Storm', phonetic: '/stórm/', portuguese: 'Tempestade', sentence: 'The storm is loud.', sentenceTranslation: 'A tempestade é barulhenta.' },
            { emoji: '🌊', english: 'Wave', phonetic: '/uéiv/', portuguese: 'Onda', sentence: 'The wave is big.', sentenceTranslation: 'A onda é grande.' },
            { emoji: '🌡️', english: 'Hot', phonetic: '/hót/', portuguese: 'Quente', sentence: 'It is hot today.', sentenceTranslation: 'Está quente hoje.' },
            { emoji: '🥶', english: 'Cold', phonetic: '/kóld/', portuguese: 'Frio', sentence: 'It is cold outside.', sentenceTranslation: 'Está frio lá fora.' },
            { emoji: '🌤️', english: 'Warm', phonetic: '/uórm/', portuguese: 'Morno', sentence: 'The weather is warm.', sentenceTranslation: 'O tempo está morno.' },
            { emoji: '⛈️', english: 'Lightning', phonetic: '/láit-ning/', portuguese: 'Raio', sentence: 'Lightning is bright.', sentenceTranslation: 'O raio é brilhante.' },
            { emoji: '🌫️', english: 'Fog', phonetic: '/fóg/', portuguese: 'Nevoeiro', sentence: 'The fog is thick.', sentenceTranslation: 'O nevoeiro é denso.' },
            { emoji: '🌪️', english: 'Tornado', phonetic: '/tornéido/', portuguese: 'Tornado', sentence: 'The tornado is scary.', sentenceTranslation: 'O tornado é assustador.' },
            { emoji: '🌊', english: 'Flood', phonetic: '/flád/', portuguese: 'Enchente', sentence: 'The flood is dangerous.', sentenceTranslation: 'A enchente é perigosa.' },
            { emoji: '🏜️', english: 'Drought', phonetic: '/dráut/', portuguese: 'Seca', sentence: 'The drought is long.', sentenceTranslation: 'A seca é longa.' },
            { emoji: '❄️', english: 'Hail', phonetic: '/héil/', portuguese: 'Granizo', sentence: 'Hail hits hard.', sentenceTranslation: 'O granizo bate forte.' },
            { emoji: '🌡️', english: 'Temperature', phonetic: '/temperatúra/', portuguese: 'Temperatura', sentence: 'Check the temperature.', sentenceTranslation: 'Verifique a temperatura.' },
            { emoji: '☀️', english: 'Sunshine', phonetic: '/sán-sháin/', portuguese: 'Luz do sol', sentence: 'I love sunshine.', sentenceTranslation: 'Eu amo a luz do sol.' },
            { emoji: '🌧️', english: 'Drizzle', phonetic: '/drízol/', portuguese: 'Chuvisco', sentence: 'Light drizzle falls.', sentenceTranslation: 'Leve chuvisco cai.' },
            { emoji: '❄️', english: 'Ice', phonetic: '/áis/', portuguese: 'Gelo', sentence: 'Ice is slippery.', sentenceTranslation: 'O gelo é escorregadio.' },
            { emoji: '💨', english: 'Breeze', phonetic: '/bríz/', portuguese: 'Brisa', sentence: 'The breeze is cool.', sentenceTranslation: 'A brisa é fresca.' },
            { emoji: '🌈', english: 'Frost', phonetic: '/fróst/', portuguese: 'Geada', sentence: 'Frost covers grass.', sentenceTranslation: 'A geada cobre a grama.' },
            { emoji: '⛈️', english: 'Thunder', phonetic: '/tándor/', portuguese: 'Trovão', sentence: 'Thunder is loud.', sentenceTranslation: 'O trovão é barulhento.' },
            { emoji: '🌊', english: 'Wave', phonetic: '/uéiv/', portuguese: 'Maré', sentence: 'High tide wave.', sentenceTranslation: 'Onda de maré alta.' }
        ]
    },
    actions: {
        title: 'Ações', icon: '🏃',
        words: [
            { emoji: '🏃', english: 'Run', phonetic: '/rán/', portuguese: 'Correr', sentence: 'I like to run.', sentenceTranslation: 'Eu gosto de correr.' },
            { emoji: '🚶', english: 'Walk', phonetic: '/uók/', portuguese: 'Andar', sentence: 'I walk to school.', sentenceTranslation: 'Eu ando para a escola.' },
            { emoji: '😴', english: 'Sleep', phonetic: '/slíp/', portuguese: 'Dormir', sentence: 'I sleep at night.', sentenceTranslation: 'Eu durmo à noite.' },
            { emoji: '🍎', english: 'Eat', phonetic: '/ít/', portuguese: 'Comer', sentence: 'I eat breakfast.', sentenceTranslation: 'Eu como o café da manhã.' },
            { emoji: '💧', english: 'Drink', phonetic: '/drínk/', portuguese: 'Beber', sentence: 'I drink water.', sentenceTranslation: 'Eu bebo água.' },
            { emoji: '📖', english: 'Read', phonetic: '/ríd/', portuguese: 'Ler', sentence: 'I read books.', sentenceTranslation: 'Eu leio livros.' },
            { emoji: '✍️', english: 'Write', phonetic: '/ráit/', portuguese: 'Escrever', sentence: 'I write stories.', sentenceTranslation: 'Eu escrevo histórias.' },
            { emoji: '🎵', english: 'Sing', phonetic: '/síng/', portuguese: 'Cantar', sentence: 'I love to sing.', sentenceTranslation: 'Eu amo cantar.' },
            { emoji: '💃', english: 'Dance', phonetic: '/dáns/', portuguese: 'Dançar', sentence: 'I like to dance.', sentenceTranslation: 'Eu gosto de dançar.' },
            { emoji: '🏊', english: 'Swim', phonetic: '/suím/', portuguese: 'Nadar', sentence: 'I swim in pool.', sentenceTranslation: 'Eu nado na piscina.' },
            { emoji: '🗣️', english: 'Talk', phonetic: '/tók/', portuguese: 'Falar', sentence: 'I talk to friends.', sentenceTranslation: 'Eu falo com amigos.' },
            { emoji: '👂', english: 'Listen', phonetic: '/lí-sen/', portuguese: 'Ouvir', sentence: 'I listen to music.', sentenceTranslation: 'Eu ouço música.' },
            { emoji: '👀', english: 'Look', phonetic: '/lúk/', portuguese: 'Olhar', sentence: 'Look at this!', sentenceTranslation: 'Olhe para isso!' },
            { emoji: '🦘', english: 'Jump', phonetic: '/djámp/', portuguese: 'Pular', sentence: 'I like to jump.', sentenceTranslation: 'Eu gosto de pular.' },
            { emoji: '🎭', english: 'Play', phonetic: '/pléi/', portuguese: 'Brincar', sentence: 'I play games.', sentenceTranslation: 'Eu brinco de jogos.' },
            { emoji: '🎤', english: 'Shout', phonetic: '/sháut/', portuguese: 'Gritar', sentence: 'Do not shout!', sentenceTranslation: 'Não grite!' },
            { emoji: '🤫', english: 'Whisper', phonetic: '/uísper/', portuguese: 'Sussurrar', sentence: 'Whisper quietly.', sentenceTranslation: 'Sussurre baixinho.' },
            { emoji: '🏃', english: 'Sprint', phonetic: '/sprínt/', portuguese: 'Sprintar', sentence: 'Sprint to the finish.', sentenceTranslation: 'Sprint para o final.' },
            { emoji: '🚶', english: 'Jog', phonetic: '/djóg/', portuguese: 'Correr', sentence: 'I jog every morning.', sentenceTranslation: 'Eu corro toda manhã.' },
            { emoji: '🧘', english: 'Stretch', phonetic: '/stréts/', portuguese: 'Alongar', sentence: 'Stretch your body.', sentenceTranslation: 'Alongue seu corpo.' },
            { emoji: '🤸', english: 'Flip', phonetic: '/flíp/', portuguese: 'Dar um mortal', sentence: 'I can flip!', sentenceTranslation: 'Eu posso dar um mortal!' },
            { emoji: '🏄', english: 'Surf', phonetic: '/sérf/', portuguese: 'Surfar', sentence: 'I surf the waves.', sentenceTranslation: 'Eu surfo nas ondas.' },
            { emoji: '🎿', english: 'Ski', phonetic: '/skí/', portuguese: 'Esquiar', sentence: 'I ski in winter.', sentenceTranslation: 'Eu esquio no inverno.' },
            { emoji: '🚴', english: 'Cycle', phonetic: '/sáikol/', portuguese: 'Andar de bike', sentence: 'I cycle to work.', sentenceTranslation: 'Eu ando de bike para o trabalho.' },
            { emoji: '🏋️', english: 'Lift', phonetic: '/líft/', portuguese: 'Levantar peso', sentence: 'I lift weights.', sentenceTranslation: 'Eu levanto peso.' }
        ]
    },
    sentences: {
        title: 'Frases', icon: '💬',
        words: [
            { emoji: '👋', english: 'Hello, how are you?', phonetic: '/hé-lóu, háu ár iú?/', portuguese: 'Olá, como vai você?', sentence: 'Hello, how are you?', sentenceTranslation: 'Olá, como vai você?' },
            { emoji: '🙏', english: 'Thank you very much', phonetic: '/sénk iú vérri máts/', portuguese: 'Muito obrigado', sentence: 'Thank you very much', sentenceTranslation: 'Muito obrigado' },
            { emoji: 'Excuse me', english: 'Excuse me', phonetic: '/iks-kiús mi/', portuguese: 'Com licença', sentence: 'Excuse me, where is the bathroom?', sentenceTranslation: 'Com licença, onde fica o banheiro?' },
            { emoji: '🙋', english: 'My name is...', phonetic: '/mai ném iz.../', portuguese: 'Meu nome é...', sentence: 'My name is John.', sentenceTranslation: 'Meu nome é João.' },
            { emoji: '❓', english: 'What is your name?', phonetic: '/uót iz iór ném?/', portuguese: 'Qual é o seu nome?', sentence: 'What is your name?', sentenceTranslation: 'Qual é o seu nome?' },
            { emoji: '❤️', english: 'I love you', phonetic: '/ái lóv iú/', portuguese: 'Eu te amo', sentence: 'I love you so much.', sentenceTranslation: 'Eu te amo muito.' },
            { emoji: '👍', english: 'Yes, I like it', phonetic: '/iés,ái láik it/', portuguese: 'Sim, eu gosto', sentence: 'Yes, I like it a lot.', sentenceTranslation: 'Sim, eu gosto muito.' },
            { emoji: '❌', english: 'No, thank you', phonetic: '/nóu, séŋk iú/', portuguese: 'Não, obrigado', sentence: 'No, thank you.', sentenceTranslation: 'Não, obrigado.' },
            { emoji: '🕐', english: 'What time is it?', phonetic: '/uót táim iz it?/', portuguese: 'Que horas são?', sentence: 'What time is it now?', sentenceTranslation: 'Que horas são agora?' },
            { emoji: '🍽️', english: 'I am hungry', phonetic: '/ái ám háŋ-gri/', portuguese: 'Estou com fome', sentence: 'I am very hungry.', sentenceTranslation: 'Estou muito com fome.' },
            { emoji: '💧', english: 'I am thirsty', phonetic: '/ái ám tér-sti/', portuguese: 'Estou com sede', sentence: 'I am so thirsty.', sentenceTranslation: 'Estou com muita sede.' },
            { emoji: '😊', english: 'Nice to meet you', phonetic: '/náis tu mít iú/', portuguese: 'Prazer em conhecê-lo', sentence: 'Nice to meet you too.', sentenceTranslation: 'Prazer em conhecê-lo também.' },
            { emoji: '🏠', english: 'Where do you live?', phonetic: '/uér du iú lív?/', portuguese: 'Onde você mora?', sentence: 'Where do you live in Brazil?', sentenceTranslation: 'Onde você mora no Brasil?' },
            { emoji: '📚', english: 'I need help', phonetic: '/ái níd hélp/', portuguese: 'Preciso de ajuda', sentence: 'I need help please.', sentenceTranslation: 'Preciso de ajuda por favor.' },
            { emoji: '🎉', english: 'Have a good day!', phonetic: '/hév e güd déi!/', portuguese: 'Tenha um bom dia!', sentence: 'Have a good day, my friend!', sentenceTranslation: 'Tenha um bom dia, meu amigo!' }
        ]
    }
};
