const vocabulary = {
    animals: {
        title: 'Animais', icon: '🐾',
        words: [
            { emoji: '🐶', english: 'Dog', phonetic: '/dóg/', portuguese: 'Cachorro', sentence: 'The dog is friendly.' },
            { emoji: '🐱', english: 'Cat', phonetic: '/kát/', portuguese: 'Gato', sentence: 'The cat sleeps a lot.' },
            { emoji: '🐦', english: 'Bird', phonetic: '/bêrd/', portuguese: 'Pássaro', sentence: 'The bird can fly.' },
            { emoji: '🐟', english: 'Fish', phonetic: '/físh/', portuguese: 'Peixe', sentence: 'The fish swims.' },
            { emoji: '🐰', english: 'Rabbit', phonetic: '/rábit/', portuguese: 'Coelho', sentence: 'The rabbit has long ears.' },
            { emoji: '🐮', english: 'Cow', phonetic: '/káu/', portuguese: 'Vaca', sentence: 'The cow gives milk.' },
            { emoji: '🐷', english: 'Pig', phonetic: '/píg/', portuguese: 'Porco', sentence: 'The pig is pink.' },
            { emoji: '🐔', english: 'Chicken', phonetic: '/chíken/', portuguese: 'Galinha', sentence: 'The chicken clucks.' },
            { emoji: '🐴', english: 'Horse', phonetic: '/hórs/', portuguese: 'Cavalo', sentence: 'The horse runs fast.' },
            { emoji: '🦁', english: 'Lion', phonetic: '/láion/', portuguese: 'Leão', sentence: 'The lion is king.' },
            { emoji: '🐘', english: 'Elephant', phonetic: '/élifant/', portuguese: 'Elefante', sentence: 'The elephant is big.' },
            { emoji: '🐵', english: 'Monkey', phonetic: '/mánki/', portuguese: 'Macaco', sentence: 'The monkey likes bananas.' },
            { emoji: '🐻', english: 'Bear', phonetic: '/bêr/', portuguese: 'Urso', sentence: 'The bear is strong.' },
            { emoji: '🐸', english: 'Frog', phonetic: '/fróg/', portuguese: 'Sapo', sentence: 'The frog jumps.' },
            { emoji: '🦆', english: 'Duck', phonetic: '/dák/', portuguese: 'Pato', sentence: 'The duck quacks.' },
            { emoji: '🐑', english: 'Sheep', phonetic: '/shíp/', portuguese: 'Ovelha', sentence: 'The sheep is soft.' },
            { emoji: ' goat', english: 'Goat', phonetic: '/góut/', portuguese: 'Cabra', sentence: 'The goat eats grass.' },
            { emoji: '🦉', english: 'Owl', phonetic: '/áol/', portuguese: 'Coruja', sentence: 'The owl is wise.' },
            { emoji: '🦅', english: 'Eagle', phonetic: '/ígol/', portuguese: 'Águia', sentence: 'The eagle flies high.' },
            { emoji: '🐺', english: 'Wolf', phonetic: '/uólf/', portuguese: 'Lobo', sentence: 'The wolf howls.' },
            { emoji: '🦊', english: 'Fox', phonetic: '/fóks/', portuguese: 'Raposa', sentence: 'The fox is clever.' },
            { emoji: '🐗', english: 'Boar', phonetic: '/bóar/', portuguese: 'Javali', sentence: 'The boar is wild.' },
            { emoji: '🦌', english: 'Deer', phonetic: '/dír/', portuguese: 'Cervo', sentence: 'The deer runs fast.' },
            { emoji: '🐢', english: 'Turtle', phonetic: '/tértol/', portuguese: 'Tartaruga', sentence: 'The turtle is slow.' },
            { emoji: '🐊', english: 'Crocodile', phonetic: '/krókodail/', portuguese: 'Crocodilo', sentence: 'The crocodile is scary.' }
        ]
    },
    food: {
        title: 'Comidas', icon: '🍎',
        words: [
            { emoji: '🍎', english: 'Apple', phonetic: '/ápol/', portuguese: 'Maçã', sentence: 'I eat an apple.' },
            { emoji: '🍌', english: 'Banana', phonetic: '/banana/', portuguese: 'Banana', sentence: 'The banana is yellow.' },
            { emoji: '🍊', english: 'Orange', phonetic: '/órinj/', portuguese: 'Laranja', sentence: 'Orange juice is good.' },
            { emoji: '🍇', english: 'Grapes', phonetic: '/gréps/', portuguese: 'Uva', sentence: 'Grapes are sweet.' },
            { emoji: '🍓', english: 'Strawberry', phonetic: '/stróbêri/', portuguese: 'Morango', sentence: 'I love strawberries.' },
            { emoji: '🍕', english: 'Pizza', phonetic: '/pítsa/', portuguese: 'Pizza', sentence: 'Pizza is delicious.' },
            { emoji: '🍔', english: 'Hamburger', phonetic: '/hámburguer/', portuguese: 'Hambúrguer', sentence: 'I want a hamburger.' },
            { emoji: '🥪', english: 'Sandwich', phonetic: '/sán-uich/', portuguese: 'Sanduíche', sentence: 'The sandwich is tasty.' },
            { emoji: '🧀', english: 'Cheese', phonetic: '/chíz/', portuguese: 'Queijo', sentence: 'Cheese is yummy.' },
            { emoji: '🥚', english: 'Egg', phonetic: '/ég/', portuguese: 'Ovo', sentence: 'I eat eggs for breakfast.' },
            { emoji: '🍞', english: 'Bread', phonetic: '/bréd/', portuguese: 'Pão', sentence: 'Bread is soft.' },
            { emoji: '🥛', english: 'Milk', phonetic: '/mílk/', portuguese: 'Leite', sentence: 'Milk is healthy.' },
            { emoji: '💧', english: 'Water', phonetic: '/uóter/', portuguese: 'Água', sentence: 'Water is refreshing.' },
            { emoji: '🧃', english: 'Juice', phonetic: '/djús/', portuguese: 'Suco', sentence: 'Juice is sweet.' },
            { emoji: '☕', english: 'Coffee', phonetic: '/cófi/', portuguese: 'Café', sentence: 'Coffee is hot.' },
            { emoji: '🍫', english: 'Chocolate', phonetic: '/chokolát/', portuguese: 'Chocolate', sentence: 'Chocolate is sweet.' },
            { emoji: '🍦', english: 'Ice Cream', phonetic: '/áis-krím/', portuguese: 'Sorvete', sentence: 'Ice cream is cold.' },
            { emoji: '🍪', english: 'Cookie', phonetic: '/kúki/', portuguese: 'Biscoito', sentence: 'The cookie is crunchy.' },
            { emoji: '🧁', english: 'Cupcake', phonetic: '/kápkeik/', portuguese: 'Cupcake', sentence: 'The cupcake is sweet.' },
            { emoji: '🍩', english: 'Donut', phonetic: '/dónat/', portuguese: 'Rosquinha', sentence: 'The donut is round.' },
            { emoji: '🌮', english: 'Taco', phonetic: '/táko/', portuguese: 'Taco', sentence: 'The taco is spicy.' },
            { emoji: '🍜', english: 'Noodles', phonetic: '/núdols/', portuguese: 'Macarrão', sentence: 'Noodles are tasty.' },
            { emoji: '🥐', english: 'Croissant', phonetic: '/kruasã/', portuguese: 'Croissant', sentence: 'The croissant is flaky.' },
            { emoji: '🥞', english: 'Pancake', phonetic: '/pánkeik/', portuguese: 'Panqueca', sentence: 'Pancakes for breakfast.' },
            { emoji: '🧈', english: 'Butter', phonetic: '/bátor/', portuguese: 'Manteiga', sentence: 'Butter on bread.' }
        ]
    },
    colors: {
        title: 'Cores', icon: '🎨',
        words: [
            { emoji: '🔴', english: 'Red', phonetic: '/réd/', portuguese: 'Vermelho', sentence: 'The car is red.' },
            { emoji: '🔵', english: 'Blue', phonetic: '/blú/', portuguese: 'Azul', sentence: 'The sky is blue.' },
            { emoji: '🟢', english: 'Green', phonetic: '/grín/', portuguese: 'Verde', sentence: 'The grass is green.' },
            { emoji: '🟡', english: 'Yellow', phonetic: '/yélou/', portuguese: 'Amarelo', sentence: 'The sun is yellow.' },
            { emoji: '🟠', english: 'Orange', phonetic: '/órinj/', portuguese: 'Laranja', sentence: 'The orange is orange.' },
            { emoji: '🟣', english: 'Purple', phonetic: '/pôrpol/', portuguese: 'Roxo', sentence: 'The flower is purple.' },
            { emoji: '⚪', english: 'White', phonetic: '/uáit/', portuguese: 'Branco', sentence: 'Snow is white.' },
            { emoji: '⚫', english: 'Black', phonetic: '/blák/', portuguese: 'Preto', sentence: 'Night is black.' },
            { emoji: '🟤', english: 'Brown', phonetic: '/bráun/', portuguese: 'Marrom', sentence: 'The dog is brown.' },
            { emoji: '🩷', english: 'Pink', phonetic: '/pínk/', portuguese: 'Rosa', sentence: 'The pig is pink.' },
            { emoji: '🩵', english: 'Light Blue', phonetic: '/láit blú/', portuguese: 'Azul Claro', sentence: 'Water is light blue.' },
            { emoji: '🩶', english: 'Gray', phonetic: '/gréi/', portuguese: 'Cinza', sentence: 'The elephant is gray.' },
            { emoji: '💎', english: 'Cyan', phonetic: '/sáian/', portuguese: 'Ciano', sentence: 'The pool is cyan.' },
            { emoji: '🌸', english: 'Magenta', phonetic: '/magentá/', portuguese: 'Magenta', sentence: 'The flower is magenta.' },
            { emoji: '🍋', english: 'Lime', phonetic: '/láim/', portuguese: 'Lima', sentence: 'The lime is sour.' },
            { emoji: '🍑', english: 'Peach', phonetic: '/pítch/', portuguese: 'Pêssego', sentence: 'The peach is soft.' },
            { emoji: '🫐', english: 'Indigo', phonetic: '/índigo/', portuguese: 'Índigo', sentence: 'The sky is indigo.' },
            { emoji: '🥥', english: 'Beige', phonetic: '/béj/', portuguese: 'Bege', sentence: 'The wall is beige.' },
            { emoji: '🥑', english: 'Olive', phonetic: '/ólív/', portuguese: 'Oliva', sentence: 'The olive is green.' },
            { emoji: '🌰', english: 'Maroon', phonetic: '/marún/', portuguese: ' Grená', sentence: 'The bag is maroon.' },
            { emoji: '🧊', english: 'Teal', phonetic: '/tíl/', portuguese: 'Azul-petróleo', sentence: 'The water is teal.' },
            { emoji: '🧤', english: 'Silver', phonetic: '/sílver/', portuguese: 'Prata', sentence: 'The ring is silver.' },
            { emoji: '🍯', english: 'Gold', phonetic: '/góld/', portuguese: 'Dourado', sentence: 'The trophy is gold.' },
            { emoji: '🌫️', english: 'Ash', phonetic: '/ásh/', portuguese: 'Cinza Claro', sentence: 'Ash is light gray.' },
            { emoji: '🥀', english: 'Burgundy', phonetic: '/bér-gundi/', portuguese: 'Borgonha', sentence: 'The wine is burgundy.' }
        ]
    },
    numbers: {
        title: 'Números', icon: '🔢',
        words: [
            { emoji: '1️⃣', english: 'One', phonetic: '/uán/', portuguese: 'Um', sentence: 'I have one cat.' },
            { emoji: '2️⃣', english: 'Two', phonetic: '/tú/', portuguese: 'Dois', sentence: 'I have two hands.' },
            { emoji: '3️⃣', english: 'Three', phonetic: '/trí/', portuguese: 'Três', sentence: 'Three little pigs.' },
            { emoji: '4️⃣', english: 'Four', phonetic: '/fór/', portuguese: 'Quatro', sentence: 'Four seasons.' },
            { emoji: '5️⃣', english: 'Five', phonetic: '/fáiv/', portuguese: 'Cinco', sentence: 'Five fingers.' },
            { emoji: '6️⃣', english: 'Six', phonetic: '/síks/', portuguese: 'Seis', sentence: 'Six eggs in a box.' },
            { emoji: '7️⃣', english: 'Seven', phonetic: '/séven/', portuguese: 'Sete', sentence: 'Seven days a week.' },
            { emoji: '8️⃣', english: 'Eight', phonetic: '/éit/', portuguese: 'Oito', sentence: 'Eight legs on spider.' },
            { emoji: '9️⃣', english: 'Nine', phonetic: '/náin/', portuguese: 'Nove', sentence: 'Nine lives for cat.' },
            { emoji: '🔟', english: 'Ten', phonetic: '/tén/', portuguese: 'Dez', sentence: 'I have ten toes.' },
            { emoji: '💯', english: 'Hundred', phonetic: '/hándred/', portuguese: 'Cem', sentence: 'One hundred points!' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣', english: 'Thousand', phonetic: '/táu-zand/', portuguese: 'Mil', sentence: 'A thousand stars.' },
            { emoji: '➕', english: 'Plus', phonetic: '/plás/', portuguese: 'Mais', sentence: 'Two plus two.' },
            { emoji: '➖', english: 'Minus', phonetic: '/máinas/', portuguese: 'Menos', sentence: 'Five minus one.' },
            { emoji: '➗', english: 'Divide', phonetic: '/diváid/', portuguese: 'Dividir', sentence: 'Divide by two.' },
            { emoji: '✖️', english: 'Multiply', phonetic: '/mátiploai/', portuguese: 'Multiplicar', sentence: 'Multiply by ten.' },
            { emoji: '0️⃣', english: 'Zero', phonetic: '/zíro/', portuguese: 'Zero', sentence: 'I have zero apples.' },
            { emoji: '1️⃣1️⃣', english: 'Eleven', phonetic: '/iléven/', portuguese: 'Onze', sentence: 'Eleven players.' },
            { emoji: '1️⃣2️⃣', english: 'Twelve', phonetic: '/tuélv/', portuguese: 'Doze', sentence: 'Twelve months.' },
            { emoji: '🔟0️⃣', english: 'Twenty', phonetic: '/tuénty/', portuguese: 'Vinte', sentence: 'Twenty students.' },
            { emoji: '1️⃣0️⃣0️⃣', english: 'Hundred', phonetic: '/hándred/', portuguese: 'Cento', sentence: 'One hundred days.' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣0️⃣', english: 'Ten Thousand', phonetic: '/tén táu-zand/', portuguese: 'Dez Mil', sentence: 'Ten thousand people.' },
            { emoji: '1️⃣0️⃣0️⃣0️⃣0️⃣0️⃣0️⃣', english: 'Million', phonetic: '/mílion/', portuguese: 'Milhão', sentence: 'A million stars.' },
            { emoji: '🧮', english: 'Billion', phonetic: '/bílion/', portuguese: 'Bilhão', sentence: 'A billion dollars.' },
            { emoji: '📈', english: 'First', phonetic: '/férst/', portuguese: 'Primeiro', sentence: 'I am first!' }
        ]
    },
    body: {
        title: 'Corpo', icon: '🦴',
        words: [
            { emoji: '👀', english: 'Eyes', phonetic: '/áis/', portuguese: 'Olhos', sentence: 'I have two eyes.' },
            { emoji: '👃', english: 'Nose', phonetic: '/nóz/', portuguese: 'Nariz', sentence: 'My nose is small.' },
            { emoji: '👂', english: 'Ear', phonetic: '/ír/', portuguese: 'Orelha', sentence: 'I hear with ears.' },
            { emoji: '👄', english: 'Mouth', phonetic: '/máus/', portuguese: 'Boca', sentence: 'I eat with mouth.' },
            { emoji: '🦷', english: 'Tooth', phonetic: '/túth/', portuguese: 'Dente', sentence: 'Brush your teeth.' },
            { emoji: '✋', english: 'Hand', phonetic: '/hánd/', portuguese: 'Mão', sentence: 'Shake my hand.' },
            { emoji: '👆', english: 'Finger', phonetic: '/fínguer/', portuguese: 'Dedo', sentence: 'Point with finger.' },
            { emoji: '🦵', english: 'Leg', phonetic: '/lég/', portuguese: 'Perna', sentence: 'I run with legs.' },
            { emoji: '🦶', english: 'Foot', phonetic: '/fút/', portuguese: 'Pé', sentence: 'My foot is big.' },
            { emoji: '💪', english: 'Arm', phonetic: '/árm/', portuguese: 'Braço', sentence: 'Strong arms!' },
            { emoji: '🧠', english: 'Brain', phonetic: '/bréin/', portuguese: 'Cérebro', sentence: 'Use your brain.' },
            { emoji: '❤️', english: 'Heart', phonetic: '/hárt/', portuguese: 'Coração', sentence: 'My heart beats fast.' },
            { emoji: '👄', english: 'Lips', phonetic: '/líps/', portuguese: 'Lábios', sentence: 'My lips are soft.' },
            { emoji: '👅', english: 'Tongue', phonetic: '/táng/', portuguese: 'Língua', sentence: 'Taste with tongue.' },
            { emoji: '💇', english: 'Hair', phonetic: '/hér/', portuguese: 'Cabelo', sentence: 'My hair is long.' },
            { emoji: '🤚', english: 'Palm', phonetic: '/pám/', portuguese: 'Palma', sentence: 'Read your palm.' },
            { emoji: '🫁', english: 'Lungs', phonetic: '/lángz/', portuguese: 'Pulmões', sentence: 'Breathe with lungs.' },
            { emoji: '🦴', english: 'Bone', phonetic: '/bón/', portuguese: 'Osso', sentence: 'Bones are strong.' },
            { emoji: '🩸', english: 'Blood', phonetic: '/blád/', portuguese: 'Sangue', sentence: 'Blood is red.' },
            { emoji: '💅', english: 'Nail', phonetic: '/néil/', portuguese: 'Unha', sentence: 'Cut your nails.' },
            { emoji: '🦷', english: 'Teeth', phonetic: '/títs/', portuguese: 'Dentes', sentence: 'Brush your teeth.' },
            { emoji: '👂', english: 'Earlobe', phonetic: '/írlob/', portuguese: 'Lóbulo', sentence: 'Earrings on earlobe.' },
            { emoji: '👁️', english: 'Eyebrow', phonetic: '/ái-brau/', portuguese: 'Sobrancelha', sentence: 'Raise your eyebrow.' },
            { emoji: '🫀', english: 'Vein', phonetic: '/véin/', portuguese: 'Veia', sentence: 'Veins carry blood.' },
            { emoji: '🦴', english: 'Skull', phonetic: '/skál/', portuguese: 'Crânio', sentence: 'Protect your skull.' }
        ]
    },
    objects: {
        title: 'Objetos', icon: '⚽',
        words: [
            { emoji: '⚽', english: 'Ball', phonetic: '/ból/', portuguese: 'Bola', sentence: 'Kick the ball.' },
            { emoji: '📚', english: 'Book', phonetic: '/búk/', portuguese: 'Livro', sentence: 'Read the book.' },
            { emoji: '✏️', english: 'Pencil', phonetic: '/pên-sol/', portuguese: 'Lápis', sentence: 'Write with pencil.' },
            { emoji: '🎒', english: 'Backpack', phonetic: '/bák-pak/', portuguese: 'Mochila', sentence: 'Carry your backpack.' },
            { emoji: '💻', english: 'Computer', phonetic: '/kom-piú-ter/', portuguese: 'Computador', sentence: 'Use the computer.' },
            { emoji: '📱', english: 'Phone', phonetic: '/fón/', portuguese: 'Celular', sentence: 'Answer the phone.' },
            { emoji: '🏠', english: 'House', phonetic: '/háus/', portuguese: 'Casa', sentence: 'This is my house.' },
            { emoji: '🚗', english: 'Car', phonetic: '/kár/', portuguese: 'Carro', sentence: 'The car is fast.' },
            { emoji: '🚌', english: 'Bus', phonetic: '/bás/', portuguese: 'Ônibus', sentence: 'Take the bus.' },
            { emoji: '✈️', english: 'Airplane', phonetic: '/éer-pléin/', portuguese: 'Avião', sentence: 'The airplane flies.' },
            { emoji: '🚂', english: 'Train', phonetic: '/tréin/', portuguese: 'Trem', sentence: 'The train goes fast.' },
            { emoji: '🚲', english: 'Bicycle', phonetic: '/báisikol/', portuguese: 'Bicicleta', sentence: 'Ride the bicycle.' },
            { emoji: '🔑', english: 'Key', phonetic: '/kí/', portuguese: 'Chave', sentence: 'Unlock the door.' },
            { emoji: '🚪', english: 'Door', phonetic: '/dór/', portuguese: 'Porta', sentence: 'Open the door.' },
            { emoji: '🪟', english: 'Window', phonetic: '/uíndo/', portuguese: 'Janela', sentence: 'Close the window.' },
            { emoji: '🛏️', english: 'Bed', phonetic: '/béd/', portuguese: 'Cama', sentence: 'Sleep in bed.' },
            { emoji: '🪑', english: 'Chair', phonetic: '/tshér/', portuguese: 'Cadeira', sentence: 'Sit on chair.' },
            { emoji: 'Table', english: 'Table', phonetic: '/téibol/', portuguese: 'Mesa', sentence: 'Eat at table.' },
            { emoji: '🛋️', english: 'Sofa', phonetic: '/sófa/', portuguese: 'Sofá', sentence: 'Relax on sofa.' },
            { emoji: '🪞', english: 'Mirror', phonetic: '/míror/', portuguese: 'Espelho', sentence: 'Look in mirror.' },
            { emoji: '🧸', english: 'Toy', phonetic: '/tóy/', portuguese: 'Brinquedo', sentence: 'Play with toy.' },
            { emoji: '🎁', english: 'Gift', phonetic: '/gift/', portuguese: 'Presente', sentence: 'Open the gift.' },
            { emoji: '🎈', english: 'Balloon', phonetic: '/balún/', portuguese: 'Balão', sentence: 'The balloon floats.' },
            { emoji: '🎯', english: 'Target', phonetic: '/tárget/', portuguese: 'Alvo', sentence: 'Hit the target.' },
            { emoji: '🧲', english: 'Magnet', phonetic: '/mágnet/', portuguese: 'Imã', sentence: 'The magnet sticks.' }
        ]
    },
    family: {
        title: 'Família', icon: '👨‍👩‍👧',
        words: [
            { emoji: '👨', english: 'Father', phonetic: '/fá-zer/', portuguese: 'Pai', sentence: 'My father is tall.' },
            { emoji: '👩', english: 'Mother', phonetic: '/má-zer/', portuguese: 'Mãe', sentence: 'My mother is kind.' },
            { emoji: '👦', english: 'Son', phonetic: '/són/', portuguese: 'Filho', sentence: 'He is my son.' },
            { emoji: '👧', english: 'Daughter', phonetic: '/dó-ter/', portuguese: 'Filha', sentence: 'She is my daughter.' },
            { emoji: '👴', english: 'Grandfather', phonetic: '/gránd-fá-zer/', portuguese: 'Avô', sentence: 'My grandfather is old.' },
            { emoji: '👵', english: 'Grandmother', phonetic: '/gránd-má-zer/', portuguese: 'Avó', sentence: 'My grandmother bakes.' },
            { emoji: '👶', english: 'Baby', phonetic: '/béibi/', portuguese: 'Bebê', sentence: 'The baby is cute.' },
            { emoji: '👫', english: 'Brother', phonetic: '/brá-zer/', portuguese: 'Irmão', sentence: 'My brother plays.' },
            { emoji: '👭', english: 'Sister', phonetic: '/sí-ster/', portuguese: 'Irmã', sentence: 'My sister sings.' },
            { emoji: '👨‍👩‍👧‍👦', english: 'Family', phonetic: '/fá-mi-li/', portuguese: 'Família', sentence: 'I love my family.' },
            { emoji: '👨‍👦', english: 'Uncle', phonetic: '/ún-kol/', portuguese: 'Tio', sentence: 'My uncle visits.' },
            { emoji: '👩‍👧', english: 'Aunt', phonetic: '/ánt/', portuguese: 'Tia', sentence: 'My aunt bakes cakes.' },
            { emoji: '💑', english: 'Couple', phonetic: '/kápol/', portuguese: 'Casal', sentence: 'They are a couple.' },
            { emoji: '🧑‍🤝‍🧑', english: 'Cousins', phonetic: '/kázins/', portuguese: 'Primos', sentence: 'We are cousins.' },
            { emoji: '👰', english: 'Wife', phonetic: '/uáif/', portuguese: 'Esposa', sentence: 'My wife is kind.' },
            { emoji: '🤵', english: 'Husband', phonetic: '/hásband/', portuguese: 'Marido', sentence: 'My husband is tall.' },
            { emoji: '🧓', english: 'Elder', phonetic: '/élder/', portuguese: 'Idoso', sentence: 'Respect your elder.' },
            { emoji: '👪', english: 'Parents', phonetic: '/pérents/', portuguese: 'Pais', sentence: 'My parents love me.' },
            { emoji: '👶', english: 'Newborn', phonetic: '/niúbórn/', portuguese: 'Recém-nascido', sentence: 'The newborn sleeps.' },
            { emoji: '🧑‍🍼', english: 'Nephew', phonetic: '/néfiu/', portuguese: 'Sobrinho', sentence: 'My nephew is cute.' },
            { emoji: '👩‍👧', english: 'Niece', phonetic: '/nís/', portuguese: 'Sobrinha', sentence: 'My niece is smart.' },
            { emoji: '👨‍👩‍👧', english: 'In-laws', phonetic: '/ín-lós/', portuguese: 'Sogrros', sentence: 'Visit the in-laws.' },
            { emoji: '💑', english: 'Stepfather', phonetic: '/stép-fá-zer/', portuguese: 'Padrasto', sentence: 'My stepfather is nice.' },
            { emoji: '👩‍👧', english: 'Stepmother', phonetic: '/stép-má-zer/', portuguese: 'Madrasta', sentence: 'My stepmother bakes.' },
            { emoji: '👶', english: 'Stepsibling', phonetic: '/stép-sibling/', portuguese: 'Irmão/a de outro pai', sentence: 'My stepsibling plays.' }
        ]
    },
    clothes: {
        title: 'Roupas', icon: '👕',
        words: [
            { emoji: '👕', english: 'Shirt', phonetic: '/shêrt/', portuguese: 'Camisa', sentence: 'Wear your shirt.' },
            { emoji: '👖', english: 'Pants', phonetic: '/pánts/', portuguese: 'Calça', sentence: 'Put on your pants.' },
            { emoji: '👗', english: 'Dress', phonetic: '/drés/', portuguese: 'Vestido', sentence: 'The dress is pretty.' },
            { emoji: '👟', english: 'Shoes', phonetic: '/shús/', portuguese: 'Sapatos', sentence: 'Tie your shoes.' },
            { emoji: '🧢', english: 'Hat', phonetic: '/hát/', portuguese: 'Boné', sentence: 'Wear your hat.' },
            { emoji: '🧣', english: 'Scarf', phonetic: '/skárf/', portuguese: 'Cachecol', sentence: 'The scarf is warm.' },
            { emoji: '🧤', english: 'Gloves', phonetic: '/glóvs/', portuguese: 'Luvas', sentence: 'Wear your gloves.' },
            { emoji: '🧥', english: 'Coat', phonetic: '/kót/', portuguese: 'Casaco', sentence: 'Put on your coat.' },
            { emoji: '🩳', english: 'Shorts', phonetic: '/shórts/', portuguese: 'Shorts', sentence: 'Wear your shorts.' },
            { emoji: '👚', english: 'Blouse', phonetic: '/bláuz/', portuguese: 'Blusa', sentence: 'The blouse is nice.' },
            { emoji: '🧦', english: 'Socks', phonetic: '/sóks/', portuguese: 'Meias', sentence: 'Wear your socks.' },
            { emoji: '👜', english: 'Bag', phonetic: '/bág/', portuguese: 'Bolsa', sentence: 'Carry your bag.' },
            { emoji: '👔', english: 'Tie', phonetic: '/táy/', portuguese: 'Gravata', sentence: 'Wear your tie.' },
            { emoji: '👖', english: 'Jeans', phonetic: '/djíns/', portuguese: 'Calça Jeans', sentence: 'Wear your jeans.' },
            { emoji: '🧥', english: 'Jacket', phonetic: '/djákit/', portuguese: 'Jaqueta', sentence: 'Put on your jacket.' },
            { emoji: '👗', english: 'Skirt', phonetic: '/skért/', portuguese: 'Saias', sentence: 'The skirt is cute.' },
            { emoji: '👙', english: 'Swimsuit', phonetic: '/suímsuit/', portuguese: 'Maiô', sentence: 'Wear your swimsuit.' },
            { emoji: '👞', english: 'Boots', phonetic: '/búts/', portuguese: 'Botas', sentence: 'Put on your boots.' },
            { emoji: '🩴', english: 'Sandals', phonetic: '/sándols/', portuguese: 'Sandálias', sentence: 'Wear your sandals.' },
            { emoji: '🧶', english: 'Sweater', phonetic: '/suéter/', portuguese: 'Suéter', sentence: 'The sweater is warm.' },
            { emoji: '🩱', english: 'Uniform', phonetic: '/iúnifórm/', portuguese: 'Uniforme', sentence: 'Wear your uniform.' },
            { emoji: '🎒', english: 'Apron', phonetic: '/épron/', portuguese: 'Avental', sentence: 'Wear your apron.' },
            { emoji: '👔', english: 'Suit', phonetic: '/siút/', portuguese: 'Terno', sentence: 'The suit is formal.' },
            { emoji: '👗', english: 'Costume', phonetic: '/kóstiúm/', portuguese: 'Fantasia', sentence: 'Wear your costume.' },
            { emoji: '🧣', english: 'Beanie', phonetic: '/bíni/', portuguese: 'Gorro', sentence: 'Wear your beanie.' }
        ]
    },
    weather: {
        title: 'Clima', icon: '☀️',
        words: [
            { emoji: '☀️', english: 'Sun', phonetic: '/són/', portuguese: 'Sol', sentence: 'The sun is hot.' },
            { emoji: '🌧️', english: 'Rain', phonetic: '/réin/', portuguese: 'Chuva', sentence: 'The rain is falling.' },
            { emoji: '❄️', english: 'Snow', phonetic: '/snóu/', portuguese: 'Neve', sentence: 'The snow is cold.' },
            { emoji: '🌤️', english: 'Cloud', phonetic: '/kláud/', portuguese: 'Nuvem', sentence: 'The cloud is white.' },
            { emoji: '💨', english: 'Wind', phonetic: '/uind/', portuguese: 'Vento', sentence: 'The wind blows.' },
            { emoji: '🌈', english: 'Rainbow', phonetic: '/réinbóu/', portuguese: 'Arco-íris', sentence: 'The rainbow is colorful.' },
            { emoji: '⛈️', english: 'Storm', phonetic: '/stórm/', portuguese: 'Tempestade', sentence: 'The storm is loud.' },
            { emoji: '🌊', english: 'Wave', phonetic: '/uéiv/', portuguese: 'Onda', sentence: 'The wave is big.' },
            { emoji: '🌡️', english: 'Hot', phonetic: '/hót/', portuguese: 'Quente', sentence: 'It is hot today.' },
            { emoji: '🥶', english: 'Cold', phonetic: '/kóld/', portuguese: 'Frio', sentence: 'It is cold outside.' },
            { emoji: '🌤️', english: 'Warm', phonetic: '/uórm/', portuguese: 'Morno', sentence: 'The weather is warm.' },
            { emoji: '⛈️', english: 'Lightning', phonetic: '/láit-ning/', portuguese: 'Raio', sentence: 'Lightning is bright.' },
            { emoji: '🌫️', english: 'Fog', phonetic: '/fóg/', portuguese: 'Nevoeiro', sentence: 'The fog is thick.' },
            { emoji: '🌪️', english: 'Tornado', phonetic: '/tornéido/', portuguese: 'Tornado', sentence: 'The tornado is scary.' },
            { emoji: '🌊', english: 'Flood', phonetic: '/flád/', portuguese: 'Enchente', sentence: 'The flood is dangerous.' },
            { emoji: '🏜️', english: 'Drought', phonetic: '/dráut/', portuguese: 'Seca', sentence: 'The drought is long.' },
            { emoji: '❄️', english: 'Hail', phonetic: '/héil/', portuguese: 'Granizo', sentence: 'Hail hits hard.' },
            { emoji: '🌡️', english: 'Temperature', phonetic: '/temperatúra/', portuguese: 'Temperatura', sentence: 'Check the temperature.' },
            { emoji: '☀️', english: 'Sunshine', phonetic: '/sán-sháin/', portuguese: 'Luz do sol', sentence: 'I love sunshine.' },
            { emoji: '🌧️', english: 'Drizzle', phonetic: '/drízol/', portuguese: 'Chuvisco', sentence: 'Light drizzle falls.' },
            { emoji: '❄️', english: 'Ice', phonetic: '/áis/', portuguese: 'Gelo', sentence: 'Ice is slippery.' },
            { emoji: '💨', english: 'Breeze', phonetic: '/bríz/', portuguese: 'Brisa', sentence: 'The breeze is cool.' },
            { emoji: '🌈', english: 'Frost', phonetic: '/fróst/', portuguese: 'Geada', sentence: 'Frost covers grass.' },
            { emoji: '⛈️', english: 'Thunder', phonetic: '/tándor/', portuguese: 'Trovão', sentence: 'Thunder is loud.' },
            { emoji: '🌊', english: 'Wave', phonetic: '/uéiv/', portuguese: 'Maré', sentence: 'High tide wave.' }
        ]
    },
    actions: {
        title: 'Ações', icon: '🏃',
        words: [
            { emoji: '🏃', english: 'Run', phonetic: '/rán/', portuguese: 'Correr', sentence: 'I like to run.' },
            { emoji: '🚶', english: 'Walk', phonetic: '/uók/', portuguese: 'Andar', sentence: 'I walk to school.' },
            { emoji: '😴', english: 'Sleep', phonetic: '/slíp/', portuguese: 'Dormir', sentence: 'I sleep at night.' },
            { emoji: '🍎', english: 'Eat', phonetic: '/ít/', portuguese: 'Comer', sentence: 'I eat breakfast.' },
            { emoji: '💧', english: 'Drink', phonetic: '/drínk/', portuguese: 'Beber', sentence: 'I drink water.' },
            { emoji: '📖', english: 'Read', phonetic: '/ríd/', portuguese: 'Ler', sentence: 'I read books.' },
            { emoji: '✍️', english: 'Write', phonetic: '/ráit/', portuguese: 'Escrever', sentence: 'I write stories.' },
            { emoji: '🎵', english: 'Sing', phonetic: '/síng/', portuguese: 'Cantar', sentence: 'I love to sing.' },
            { emoji: '💃', english: 'Dance', phonetic: '/dáns/', portuguese: 'Dançar', sentence: 'I like to dance.' },
            { emoji: '🏊', english: 'Swim', phonetic: '/suím/', portuguese: 'Nadar', sentence: 'I swim in pool.' },
            { emoji: '🗣️', english: 'Talk', phonetic: '/tók/', portuguese: 'Falar', sentence: 'I talk to friends.' },
            { emoji: '👂', english: 'Listen', phonetic: '/lí-sen/', portuguese: 'Ouvir', sentence: 'I listen to music.' },
            { emoji: '👀', english: 'Look', phonetic: '/lúk/', portuguese: 'Olhar', sentence: 'Look at this!' },
            { emoji: ' jump', english: 'Jump', phonetic: '/djámp/', portuguese: 'Pular', sentence: 'I like to jump.' },
            { emoji: '🎭', english: 'Play', phonetic: '/pléi/', portuguese: 'Brincar', sentence: 'I play games.' },
            { emoji: '🎤', english: 'Shout', phonetic: '/sháut/', portuguese: 'Gritar', sentence: 'Do not shout!' },
            { emoji: '🤫', english: 'Whisper', phonetic: '/uísper/', portuguese: 'Sussurrar', sentence: 'Whisper quietly.' },
            { emoji: '🏃', english: 'Sprint', phonetic: '/sprínt/', portuguese: 'Sprintar', sentence: 'Sprint to the finish.' },
            { emoji: '🚶', english: 'Jog', phonetic: '/djóg/', portuguese: 'Correr', sentence: 'I jog every morning.' },
            { emoji: '🧘', english: 'Stretch', phonetic: '/stréts/', portuguese: 'Alongar', sentence: 'Stretch your body.' },
            { emoji: '🤸', english: 'Flip', phonetic: '/flíp/', portuguese: 'Dar um mortal', sentence: 'I can flip!' },
            { emoji: '🏄', english: 'Surf', phonetic: '/sérf/', portuguese: 'Surfar', sentence: 'I surf the waves.' },
            { emoji: '🎿', english: 'Ski', phonetic: '/skí/', portuguese: 'Esquiar', sentence: 'I ski in winter.' },
            { emoji: '🚴', english: 'Cycle', phonetic: '/sáikol/', portuguese: 'Andar de bike', sentence: 'I cycle to work.' },
            { emoji: '🏋️', english: 'Lift', phonetic: '/líft/', portuguese: 'Levantar peso', sentence: 'I lift weights.' }
        ]
    },
    sentences: {
        title: 'Frases', icon: '💬',
        words: [
            { emoji: '👋', english: 'Hello, how are you?', phonetic: '/hé-lóu, háu ár iú?/', portuguese: 'Olá, como vai você?', sentence: 'Hello, how are you?' },
            { emoji: '🙏', english: 'Thank you very much', phonetic: '/sénk iú vérri máts/', portuguese: 'Muito obrigado', sentence: 'Thank you very much' },
            { emoji: 'Excuse me', english: 'Excuse me', phonetic: '/iks-kiús mi/', portuguese: 'Com licença', sentence: 'Excuse me, where is the bathroom?' },
            { emoji: '🙋', english: 'My name is...', phonetic: '/mai ném iz.../', portuguese: 'Meu nome é...', sentence: 'My name is John.' },
            { emoji: '❓', english: 'What is your name?', phonetic: '/uót iz iór ném?/', portuguese: 'Qual é o seu nome?', sentence: 'What is your name?' },
            { emoji: '❤️', english: 'I love you', phonetic: '/ái lóv iú/', portuguese: 'Eu te amo', sentence: 'I love you so much.' },
            { emoji: '👍', english: 'Yes, I like it', phonetic: '/iés,ái láik it/', portuguese: 'Sim, eu gosto', sentence: 'Yes, I like it a lot.' },
            { emoji: '❌', english: 'No, thank you', phonetic: '/nóu, séŋk iú/', portuguese: 'Não, obrigado', sentence: 'No, thank you.' },
            { emoji: '🕐', english: 'What time is it?', phonetic: '/uót táim iz it?/', portuguese: 'Que horas são?', sentence: 'What time is it now?' },
            { emoji: '🍽️', english: 'I am hungry', phonetic: '/ái ám háŋ-gri/', portuguese: 'Estou com fome', sentence: 'I am very hungry.' },
            { emoji: '💧', english: 'I am thirsty', phonetic: '/ái ám tér-sti/', portuguese: 'Estou com sede', sentence: 'I am so thirsty.' },
            { emoji: '😊', english: 'Nice to meet you', phonetic: '/náis tu mít iú/', portuguese: 'Prazer em conhecê-lo', sentence: 'Nice to meet you too.' },
            { emoji: '🏠', english: 'Where do you live?', phonetic: '/uér du iú lív?/', portuguese: 'Onde você mora?', sentence: 'Where do you live in Brazil?' },
            { emoji: '📚', english: 'I need help', phonetic: '/ái níd hélp/', portuguese: 'Preciso de ajuda', sentence: 'I need help please.' },
            { emoji: '🎉', english: 'Have a good day!', phonetic: '/hév e güd déi!/', portuguese: 'Tenha um bom dia!', sentence: 'Have a good day, my friend!' }
        ]
    }
};
